describe("parse_sdp", function()
  it("loads without error", function()
    local sdp = require("parse_sdp")
    assert.is_table(sdp)
  end)
end)

describe("grammar.tokenize_line", function()
  local grammar = require("lib.grammar")

  it("parses a valid CRLF line", function()
    local t, v, offset = grammar.tokenize_line("v=0\r\n")
    assert.equal("v", t)
    assert.equal("0", v)
    assert.equal(3, offset)
  end)

  it("parses a valid LF-only line", function()
    local t, v, offset = grammar.tokenize_line("s=My Session\n")
    assert.equal("s", t)
    assert.equal("My Session", v)
    assert.equal(3, offset)
  end)

  it("parses a line with no trailing newline", function()
    local t, v, offset = grammar.tokenize_line("v=0")
    assert.equal("v", t)
    assert.equal("0", v)
    assert.equal(3, offset)
  end)

  it("parses a line with a complex value", function()
    local t, v, offset = grammar.tokenize_line("o=- 0 0 IN IP4 127.0.0.1\r\n")
    assert.equal("o", t)
    assert.equal("- 0 0 IN IP4 127.0.0.1", v)
    assert.equal(3, offset)
  end)

  it("rejects empty input", function()
    local t, pos = grammar.tokenize_line("")
    assert.is_nil(t)
    assert.is_number(pos)
  end)

  it("rejects a line with no equals sign", function()
    local t, pos = grammar.tokenize_line("invalid\r\n")
    assert.is_nil(t)
    assert.is_number(pos)
  end)

  it("rejects a line with multi-char type field", function()
    local t, pos = grammar.tokenize_line("ab=value\r\n")
    assert.is_nil(t)
    assert.is_number(pos)
  end)

  it("rejects a line with non-alpha type character", function()
    local t, pos = grammar.tokenize_line("1=value\r\n")
    assert.is_nil(t)
    assert.is_number(pos)
  end)

  it("rejects a line with an empty value", function()
    local t, pos = grammar.tokenize_line("v=\r\n")
    assert.is_nil(t)
    assert.is_number(pos)
  end)

  it("returns failure position 1 for non-alpha type", function()
    local t, pos = grammar.tokenize_line("1=value\r\n")
    assert.is_nil(t)
    assert.equal(1, pos)
  end)

  it("returns failure position after type char for multi-char type", function()
    local t, pos = grammar.tokenize_line("ab=value\r\n")
    assert.is_nil(t)
    assert.equal(2, pos)  -- failed after consuming 'a'
  end)

  it("returns failure position at value start for empty value", function()
    local t, pos = grammar.tokenize_line("v=\r\n")
    assert.is_nil(t)
    assert.equal(3, pos)  -- failed at position 3 where value was expected
  end)
end)
